LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

CXX_SHARED_ROOT := $(NDK_ROOT)/sources/cxx-stl/llvm-libc++/libs/$(TARGET_ARCH_ABI)


#LOCAL_CFLAGS += -fPIE
#LOCAL_LDFLAGS += -fPIE -pie
#LOCAL_CPPFLAGS += -std=gnu++0x -fPIE -ggdb

COMMON_SRC_FILES := gst-setup.c

TOOL_NAME := gst-launch
LOCAL_MODULE     := $(TOOL_NAME)
LOCAL_SRC_FILES  := $(TOOL_NAME).c $(COMMON_SRC_FILES)
LOCAL_SHARED_LIBRARIES := gstreamer_android
#LOCAL_SHARED_LIBRARIES += c++_shared
LOCAL_LDFLAGS += -lc++_shared
#LOCAL_LDLIBS := -L$(CXX_SHARED_ROOT) 
include $(BUILD_EXECUTABLE)

include $(CLEAR_VARS)

TOOL_NAME := gst-inspect
LOCAL_MODULE     := $(TOOL_NAME)
LOCAL_SRC_FILES  := $(TOOL_NAME).c $(COMMON_SRC_FILES)
LOCAL_SHARED_LIBRARIES := gstreamer_android
#LOCAL_SHARED_LIBRARIES += c++_shared
LOCAL_LDFLAGS += -lc++_shared
#LOCAL_LDLIBS := -L$(CXX_SHARED_ROOT) 
include $(BUILD_EXECUTABLE)

ifndef GSTREAMER_ROOT_ANDROID
$(error GSTREAMER_ROOT_ANDROID is not defined!)
endif

ifeq ($(TARGET_ARCH_ABI),armeabi)
GSTREAMER_ROOT        := $(GSTREAMER_ROOT_ANDROID)/arm
else ifeq ($(TARGET_ARCH_ABI),armeabi-v7a)
GSTREAMER_ROOT        := $(GSTREAMER_ROOT_ANDROID)/armv7
else ifeq ($(TARGET_ARCH_ABI),arm64-v8a)
GSTREAMER_ROOT        := $(GSTREAMER_ROOT_ANDROID)/arm64
else ifeq ($(TARGET_ARCH_ABI),x86)
GSTREAMER_ROOT        := $(GSTREAMER_ROOT_ANDROID)/x86
else ifeq ($(TARGET_ARCH_ABI),x86_64)
GSTREAMER_ROOT        := $(GSTREAMER_ROOT_ANDROID)/x86_64
else
$(error Target arch ABI not supported: $(TARGET_ARCH_ABI))
endif

GSTREAMER_NDK_BUILD_PATH  := $(GSTREAMER_ROOT)/share/gst-android/ndk-build/
include $(GSTREAMER_NDK_BUILD_PATH)/plugins.mk
GSTREAMER_PLUGINS         := $(GSTREAMER_PLUGINS_CORE) $(GSTREAMER_PLUGINS_PLAYBACK) $(GSTREAMER_PLUGINS_CODECS) $(GSTREAMER_PLUGINS_NET) $(GSTREAMER_PLUGINS_SYS) $(GSTREAMER_PLUGINS_CODECS_RESTRICTED) $(GSTREAMER_PLUGINS_NET_RESTRICTED) $(GSTREAMER_PLUGINS_CAPTURE)
GSTREAMER_EXTRA_LIBS      := -liconv
GSTREAMER_EXTRA_DEPS      := gstreamer-video-1.0
include $(GSTREAMER_NDK_BUILD_PATH)/gstreamer-1.0.mk
